### PR TITLE
Fixed --> Typo: running fafter script (#47)

### LINKED ISSUE #47: Typo: "running fafter script"
present in mssql, mysql and postgres providers, there's an additional "F" character being added in the log line for running before/after scripts. 

Remove it please!

```
            self.logger.info(f"Running f{title} script #{i} \"{script[:50]}\"")
```

### PR DESCRIPTION
**Pull request by itsabhianant**
Fixes #47

### CODE REVIEW

**Comment by itsabhianant** [comment]
Hi, 

I fixed the issue stated on #47. Please let me know if something else is to be done related to the same issue.

Best,
Abhishek

**Comment by jerometwell** [comment]
Hi @itsabhianant can you add a line to the [CHANGELOG.md](https://github.com/jerometwell/pynonymizer/blob/master/CHANGELOG.md) file describing your change (to humans)

it's one of the things mentioned in [CONTRIBUTING.md](https://github.com/jerometwell/pynonymizer/blob/master/CONTRIBUTING.md). 

Also, as an aside, `my-new-feature` isn't a very descriptive branch name. It's not a dealbreaker, but normally this information gets captured in merge commits and stuff so it helps to use that to describe what the branch was for originally. 

Otherwise looks good!

**Comment by itsabhianant** [comment]
Where exactly I have to write about the recent changes in CHANGELOG.md?

**Comment by jerometwell** [comment]
from [CONTRIBUTING.md](https://github.com/jerometwell/pynonymizer/blob/master/CONTRIBUTING.md)
> Add an entry to the CHANGELOG.md file, under the [Unreleased] section.
> [...]
> Try to describe what you've achieved from a user-facing perspective

**Pull request closed without merging**
